### ISSUE TITLE
pylsp hangs in Atom if a file is saved immediately after change, due to mypy

### ISSUE THREAD

**Issue by kparal** [Richardk2n/mypy-ls#12] opened 2021-06-25 15:12 UTC
Into the virtualenv for my project, I installed
```
python-lsp-server[rope,pyflakes,pycodestyle]
mypy-ls
```
Then I installed [ide-python](https://github.com/atom-community/ide-python) plugin into the Atom editor, and started Atom from the virtualenv. File linting works fine from both `pycodestyle` and `mypy`, for example a line like this shows a mypy error:
```
x: str = 1
```

Everything is fine when I edit the file, and when I wait a while and save it. However, if I change a file and them **immediately** press Ctrl+S to save it, I see the following traceback in Atom's Dev Console:
```
logger.ts:19 Python (pyls) stderr   File "/usr/lib64/python3.9/threading.py", line 1266, in run
logger.ts:19 Python (pyls) stderr     self.function(*self.args, **self.kwargs)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pylsp/_utils.py", line 33, in run
logger.ts:19 Python (pyls) stderr     return func(*args, **kwargs)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pylsp/python_lsp.py", line 274, in lint
logger.ts:19 Python (pyls) stderr     flatten(self._hook('pylsp_lint', doc_uri, is_saved=is_saved))
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pylsp/python_lsp.py", line 155, in _hook
logger.ts:19 Python (pyls) stderr     return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
logger.ts:19 Python (pyls) stderr     return self._hookexec(self, self.get_hookimpls(), kwargs)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
logger.ts:19 Python (pyls) stderr     return self._inner_hookexec(hook, methods, kwargs)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/manager.py", line 337, in traced_hookexec
logger.ts:19 Python (pyls) stderr     return outcome.get_result()
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
logger.ts:19 Python (pyls) stderr     raise ex[1].with_traceback(ex[2])
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/callers.py", line 52, in from_call
logger.ts:19 Python (pyls) stderr     result = func()
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/manager.py", line 335, in <lambda>
logger.ts:19 Python (pyls) stderr     outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
logger.ts:19 Python (pyls) stderr     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
logger.ts:19 Python (pyls) stderr     return outcome.get_result()
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
logger.ts:19 Python (pyls) stderr     raise ex[1].with_traceback(ex[2])
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
logger.ts:19 Python (pyls) stderr     res = hook_impl.function(*args)
logger.ts:19 Python (pyls) stderr   File "/home/kparal/devel/.venv/blockerbugs/lib/python3.9/site-packages/mypy_ls/plugin.py", line 173, in pylsp_lint
logger.ts:19 Python (pyls) stderr     report, errors, _ = mypy_api.run(args)
logger.ts:19 Python (pyls) stderr   File "mypy/api.py", line 69, in run
logger.ts:19 Python (pyls) stderr   File "mypy/api.py", line 58, in _run
logger.ts:19 Python (pyls) stderr   File "mypy/api.py", line 69, in <lambda>
logger.ts:19 Python (pyls) stderr   File "mypy/main.py", line 87, in main
logger.ts:19 Python (pyls) stderr   File "mypy/main.py", line 165, in run_build
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 179, in build
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 254, in _build
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 2644, in dispatch
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 2868, in load_graph
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 1848, in __init__
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 1307, in validate_meta
logger.ts:19 Python (pyls) stderr   File "mypy/build.py", line 698, in getmtime
logger.ts:19 Python (pyls) stderr   File "mypy/metastore.py", line 90, in getmtime
logger.ts:19 Python (pyls) stderr   File "/usr/lib64/python3.9/genericpath.py", line 55, in getmtime
logger.ts:19 Python (pyls) stderr     return os.stat(filename).st_mtime
logger.ts:19 Python (pyls) stderr FileNotFoundError: [Errno 2] No such file or directory: '.mypy_cache/3.9/blockerbugs/models/update.data.json'
```

After this error, file linting no longer works (neither `mypy`, nor `pycodestyle`). The linting output is stuck to the last state. The error repeats on every file change. Furthermore, the error persists even after restarting the editor. The only way to resolve it seems to be `rm -rf .mypy_cache` and a clean editor start. And if I save the file too quickly, the problem repeats.

The file it complains about (in this case `blockerbugs/models/update(.py)` is different every time. It is clearly some kind of a race condition.

I don't have much experience with pyls nor mypy. Is this a pyls error or a mypy-ls or a mypy error? Can I provide additional helpful info?

FWIW, this problem doesn't happen if I use [linter-mypy](https://github.com/elarivie/linter-mypy) plugin, which calls `mypy` directly and not through the `python-lsp-server`+`mypy-ls`. Executing `mypy` on a commandline is not a problem either.

Versions:
```
$ pip freeze | grep -E '(lsp|mypy)'
mypy==0.910
mypy-extensions==0.4.3
mypy-ls==0.4.1
pylsp-mypy==0.5.0
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.0.1
```

**Comment by Richardk2n** [comment] 2021-06-25 17:28
I am currently in the process of renaming the project from mypy-ls to pylsp-mypy if the change is well received that is. You seem to have both installed, so you have it installed twice basically. The two installations might interfere with each other.

**Comment by kparal** [comment] 2021-06-28 10:11
You're right, I had both. I created a completely new virtualenv, installed project dependencies, and `mypy-ls`, nothing else. The problem is still the same.
```
$ pip freeze | grep -E '(lsp|mypy)'
mypy==0.910
mypy-extensions==0.4.3
mypy-ls==0.4.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.1.0
```

**Comment by kparal** [comment] 2021-06-29 17:45
I have a suspicion that the problem might be in the `ide-python` Atom plugin. It doesn't seem to correctly support `python-lsp-server` (only the older `python-language-server`). For example, it can't configure which linters to enable with the lsp-server. This error might be caused by some API change between those two.

**Comment by Richardk2n** [comment] 2021-07-03 13:25
I would agree with you, that this looks a lot like a race condition.
I would assume, that mypy at some point in the run deletes parts of the cache, so if it runs twice simultaneously one of the instances crashes because the other one deleted the files it's trying to read.

Given that you did not provide your settings, I am assuming, that you have the defaults active. That means live mode is active, which causes a call to mypy all the time while you type. These calls are rather slow, so, if pylsp (or your editor) would not provide some sort of thread safety, that would crash.

Given that is not the case, the cause for the issue is, that this thread safety gets not provided for the call caused by saving vs the ones caused by typing.

There are several quick fixes:

- Wait a little until saving.
- Turn live mode of.
- Define a lock in plugin.py which gets acquired at the start of pylsp_lint and released at the end

I do not think the plugins are supposed to provide thread safety (I looked at others and saw nothing like that).

As far as i know, the API did not change, but the namespace did. This might cause issues in an editor not supporting it.

I would recommend asking the authors of your editor if pylsp is supported.

I am closing this for now, as I think, I am supposed to implement thread safety, should I be wrong about that, please feel free to reopen this and let me know.

**Closed by Richardk2n** 2021-07-03 13:25 UTC
